
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/codegangsta/cli"
  version = "1.20.0"

[[constraint]]
  name = "github.com/qframe/cache-inventory"
  version = "0.3.3"

[[constraint]]
  name = "github.com/qframe/collector-docker-events"
  version = "0.3.1"

[[constraint]]
  name = "github.com/qframe/collector-docker-logs"
  version = "0.4.2"

[[constraint]]
  name = "github.com/qframe/collector-internal"
  version = "0.1.3"

[[constraint]]
  name = "github.com/qframe/filter-grok"
  version = "0.1.14"

[[constraint]]
  name = "github.com/qframe/handler-elasticsearch"
  version = "0.1.14"

[[constraint]]
  name = "github.com/qframe/handler-influxdb"
  version = "0.2.1"

[[constraint]]
  name = "github.com/qframe/types"
  version = "0.1.9"

[[constraint]]
  branch = "master"
  name = "github.com/zpatrick/go-config"
